export const ticketAction = {
  CURRENT_TICKET_TITLE: "current_ticket_title",
  CURRENT_TICKET_DESCRIPTION: "current_ticket_description",
  CURRENT_TICKET_ASSIGNED_TO: "current_ticket_assignedTo",
  ADD_NEW_TICKET: "add_new_ticket",
  UPDATE_THIS_TICKET: "update_this_ticket",
  DELETE_THIS_TICKET: "delete_this_ticket",
  REMOVE_FROM_DELETED_LIST: "remove_from_deleted_list",
  TICKET_TO_UPDATE: "ticket_to_update",
  TICKET_TO_UPDATE_CHANGES: "ticket_to_update_changes",
  RAISE_TOAST: "toggle_toast_message",
  ADD_TO_DELETE_LIST: "add_to_delete_list",
  SET_ERROR_TITLE: "set_error_title",
  SET_ERROR_DESCRIPTION: "set_error_description",
  RESET_ERROR: "reset_error",
  IMPORT_DUMMY_DATA: "import_dummy_data",
};
