export const ticketAction = {
  CURRENT_TICKET_TITLE: "current_ticket_title",
  CURRENT_TICKET_DESCRIPTION: "current_ticket_description",
  CURRENT_TICKET_ASSIGNED_TO: "current_ticket_assignedTo",
  CURRENT_TICKET_STATUS: "current_ticket_status",
  ADD_NEW_TICKET: "add_new_ticket",
  UPDATE_THIS_TICKET: "update_this_ticket",
  ARCHIVE_THIS_TICKET: "archive_this_ticket",
  REMOVE_FROM_ARCHIVED_LIST: "remove_from_archived_list",
  TICKET_TO_UPDATE: "ticket_to_update",
  TICKET_TO_UPDATE_CHANGES: "ticket_to_update_changes",
  RAISE_TOAST: "toggle_toast_message",
  ADD_TO_ARCHIVE_LIST: "add_to_archive_list",
  SET_ERROR_TITLE: "set_error_title",
  SET_ERROR_DESCRIPTION: "set_error_description",
  SET_ERROR_NAME: "set_error_name",
  SET_ERROR_EMAIL: "set_error_email",
  SET_ERROR_PASSWORD: "set_error_password",
  SET_ERROR_SIGNIN: "set_error_signin",
  RESET_ERROR: "reset_error",
  IMPORT_DUMMY_DATA: "import_dummy_data",
};
